// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxw5P2nk2ionYqe-OKPGR4IzufFUbh25s',
    appId: '1:47547648402:web:88b2bcde75c934e27d194b',
    messagingSenderId: '47547648402',
    projectId: 'ostad-assignment',
    authDomain: 'ostad-assignment.firebaseapp.com',
    databaseURL: 'https://ostad-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-assignment.firebasestorage.app',
    measurementId: 'G-MTJW6JTCNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAR2ooPriLYljAaYknu440s8l_6spoOog',
    appId: '1:47547648402:android:ae5b7cc4561767837d194b',
    messagingSenderId: '47547648402',
    projectId: 'ostad-assignment',
    databaseURL: 'https://ostad-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6xYaPH9iSapi4gKydCBP2Iha97rQNWk',
    appId: '1:47547648402:ios:9183038980ed3ac57d194b',
    messagingSenderId: '47547648402',
    projectId: 'ostad-assignment',
    databaseURL: 'https://ostad-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-assignment.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS6xYaPH9iSapi4gKydCBP2Iha97rQNWk',
    appId: '1:47547648402:ios:9183038980ed3ac57d194b',
    messagingSenderId: '47547648402',
    projectId: 'ostad-assignment',
    databaseURL: 'https://ostad-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-assignment.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxw5P2nk2ionYqe-OKPGR4IzufFUbh25s',
    appId: '1:47547648402:web:cadba07ec2358bb97d194b',
    messagingSenderId: '47547648402',
    projectId: 'ostad-assignment',
    authDomain: 'ostad-assignment.firebaseapp.com',
    databaseURL: 'https://ostad-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-assignment.firebasestorage.app',
    measurementId: 'G-S38CKR11JJ',
  );

}